---
- name: loopdemo
  hosts: web
  vars_file:
    - loop_vars.yaml
  tasks:
    - name: install pkg in loop
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ pkg }}"

    - name: starinting services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ srv }}"
...
