---
#this is a play
- name: sample playbook
  hosts: web
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: present
    - name: starting the service
      service:
        name: httpd
        state: started
    - name: create document root index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: allow http in firewall
      firewalld:
        service: http
        state: enabled

- name: verify web server
  hosts: localhost
  tasks:
    - uri:
        url: http://192.168.56.102/index.html
        status_code: 200
        return_content: yes
      register: output

    - debug: 
        var: output
...
